Repository one-acre-fund/helm-paymenthub, pull requests merged in 2023-06, with the labels that each got.

#26 reconfigure startup probes for erply and mpesa
  helm/ph-ee-engine/templates/connector-ams-erply.yaml
  helm/ph-ee-engine/templates/connector-mpesa.yaml
Labels: size/XL

#27 Add fineract ams connector templates
  helm/ph-ee-engine/templates/connector-ams-fineract.yaml
  helm/ph-ee-engine/values.yaml
Labels: size/L

#29 add timeout for startup probes
  helm/ph-ee-engine/templates/connector-ams-paygops.yaml
  helm/ph-ee-engine/templates/connector-ams-roster.yaml
Labels: size/XS
