Repository one-acre-fund/helm-paymenthub, pull requests merged in 2023-08, with the labels that each got.

#31 Add airtel connector template
  helm/ph-ee-engine/templates/connector-airtel.yaml
  helm/ph-ee-engine/values.yaml
Labels: size/L

#32 disable notifications
  helm/ph-ee-engine/values.yaml
Labels: size/XS

#34 Define mpesa envs for fineract and odoo connectors
  helm/ph-ee-engine/templates/connector-mpesa.yaml
  helm/ph-ee-engine/values.yaml
Labels: size/M
