Repository one-acre-fund/helm-paymenthub, pull requests merged in 2024-03, with the labels that each got.

#45 Define envs for fineract mpesa paybill transactions
  helm/ph-ee-engine/templates/connector-mpesa.yaml
  helm/ph-ee-engine/values.yaml
Labels: size/S

#46 Add deployment config for TNM connector
  helm/ph-ee-engine/templates/connector-tnm.yaml
  helm/ph-ee-engine/values.yaml
Labels: size/L

#47 feat/SER-1853 Remove unnecessary configs
  helm/ph-ee-engine/values.yaml
Labels: size/XS

#48 Update startup probe port
  helm/ph-ee-engine/templates/connector-tnm.yaml
Labels: size/XS

#49 Update connector-ams-fineract.yaml
  helm/ph-ee-engine/templates/connector-ams-fineract.yaml
Labels: size/S

#50 Add TNM connector channel env
  helm/ph-ee-engine/templates/connector-tnm.yaml
  helm/ph-ee-engine/values.yaml
Labels: size/XS
